name: Discord Notification

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "content": "🚀 Deploy realizado com sucesso!",
                "embeds": [{
                  "title": "GitHub Actions",
                  "description": "Commit ou PR executado com sucesso!",
                  "color": 5814783
                }]
              }' \
          ${{ secrets.DISCORD_WEBHOOK }}